from django.conf.urls.defaults import patterns

urlpatterns = patterns('',
    (r'(?P<dataset_id>\d+)/explore/$', 'plexigraph.graphview.views.explore'),
    (r'explore/relayout/$', 'plexigraph.graphview.views.relayout'),
    (r'explore/reset/$', 'plexigraph.graphview.views.reset'),
    (r'explore/delete_nodes/(?P<node_list>[-\w,]+)$', 
            'plexigraph.graphview.views.delete_nodes'),
    (r'explore/delete_edges/(?P<edge_list>[-\w,]+)$', 
            'plexigraph.graphview.views.delete_edges'),
    (r'explore/expand_nodes/(?P<node_list>[-\w,]+)$', 
            'plexigraph.graphview.views.expand_nodes'),
    (r'explore/toggle_nodes/(?P<node_type>\w+)$',
            'plexigraph.graphview.views.toggle_nodes'),
    (r'explore/load_state/$', 'plexigraph.graphview.views.load_state'),
    (r'explore/save_state/$', 'plexigraph.graphview.views.save_state'),
    (r'explore/delete_isolated/$', 'plexigraph.graphview.views.delete_isolated'),
    (r'explore/interactor_query/$', 
         'plexigraph.graphview.views.interactor_query'),
    (r'$', 'plexigraph.graphview.views.index'),
)
